package com.hear2.anniversary.dto;

import com.hear2.anniversary.support.AnniversaryDdayType;
import com.hear2.anniversary.support.AnniversaryType;
import com.hear2.anniversary.support.AutoAnniversaryType;
import lombok.Builder;

import java.time.LocalDate;
import java.util.List;

@Builder
public record AnniversaryResponse(
        Long id,
        String autoKey,
        String title,
        AnniversaryType type,
        LocalDate date,
        LocalDate displayDate,
        AnniversaryDdayType ddayType,
        int dday,
        String ddayLabel,
        boolean repeatYearly,
        boolean shared,
        String icon,
        String color,
        List<Integer> notifyDays,
        boolean autoGenerated,
        AutoAnniversaryType autoGeneratedType,
        Long createdBy,
        boolean editable,
        boolean hideable
) {
}
